services:

  cron:
    image: savdev/alpine-dcron
    build:
      context: ./build
    volumes:
      - ./cron/tasks:/etc/cron.d
      - ./cron/scripts:/scripts
    environment:
      - TZ=${TZ:-Europe/Berlin}
      - |
        CRON_TASKS=
        */1       *       *       *       *       echo hello from on-fly task 1 
        */2       *       *       *       *       echo hello from on-fly on-fly task 2
        *       *       *       *       *       wrong_command
        completely * wrong * expression
    networks:
      - default