services:

  cron:
    image: savdev/alpine-dcron
    build:
      context: ./build
    volumes:
      - ./cron/tasks:/etc/cron.d
      - ./cron/scripts:/scripts
    environment:
      - TZ=${TZ:-Europe/Berlin}
      - |
        CRON_TASKS=
        *       *       *       *       *       echo hello from on-fly task 1 
        *       *       *       *       *       curl -i -X HEAD -w "\n" -H 'Content-Type: application/json' http://www.google.de
        *       *       *       *       *       wrong_command
        completely * wrong cron * expression example
    networks:
      - default